select
    order_id,
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix                        as zip_code_prefix,
    {{ date_key('purchased_at') }}                  as purchase_date_key,
    {{ date_key('delivered_to_customer_at') }}      as delivered_date_key,
    {{ date_key('estimated_delivery_date') }}       as estimated_delivery_date_key,
    order_status,
    is_canceled,
    is_delivered,
    is_late,
    used_voucher,
    primary_payment_type,
    purchased_at,
    approved_at,
    delivered_to_carrier_at,
    delivered_to_customer_at,
    estimated_delivery_date,
    item_count,
    seller_count,
    items_value,
    freight_value,
    order_value,
    payment_value,
    payment_count,
    max_installments,
    purchase_to_approval_days,
    purchase_to_carrier_days,
    delivery_lead_days,
    estimated_lead_days,
    days_vs_estimate,
    review_count,
    avg_review_score
from {{ ref('int_order_enriched') }}
