"""Generate docs/lineage.md from the ref()/source() calls in the dbt models.

The Mermaid graph is derived from the SQL, never written by hand, so it cannot drift from the
project (tests/unit/test_lineage_doc.py regenerates it and compares).

Usage: python scripts/build_lineage.py [--check]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS = ROOT / "dbt" / "models"
OUT = ROOT / "docs" / "lineage.md"

REF = re.compile(r"ref\(\s*'([a-z0-9_]+)'\s*\)")
SOURCE = re.compile(r"source\(\s*'src'\s*,\s*'([a-z0-9_]+)'\s*\)")
LAYERS = (
    ("src", "src (typed source tables)"),
    ("stg", "staging (views)"),
    ("int", "intermediate (views)"),
    ("core", "warehouse: dimensions and facts"),
    ("mart", "marts: business aggregates"),
)

HEADER = """# Lineage

Generated by `scripts/build_lineage.py` from the `ref()` / `source()` calls in `dbt/models`
(do not edit by hand; `tests/unit/test_lineage_doc.py` fails if it is stale). The same graph
is available interactively with `dbt docs generate && dbt docs serve`.

`src.*` are the typed tables loaded by `olist stage`; everything to the right is dbt.
Only the last two layers are published (`warehouse`, `marts`). Grain, keys and measures of
each fact: [data_model.md](data_model.md). Column descriptions and tests live next to the
models (`_staging.yml`, `_intermediate.yml`, `_core.yml`, `_business.yml`).

"""


def layer(model: str) -> str:
    if model.startswith(("dim_", "fct_")):
        return "core"
    return model.split("_", 1)[0]


def edges() -> list[tuple[str, str]]:
    found: set[tuple[str, str]] = set()
    for sql in MODELS.rglob("*.sql"):
        text = sql.read_text(encoding="utf-8")
        found |= {(ref, sql.stem) for ref in REF.findall(text)}
        found |= {(f"src_{table}", sql.stem) for table in SOURCE.findall(text)}
    return sorted(found)


def render() -> str:
    pairs = edges()
    nodes = sorted({n for pair in pairs for n in pair})
    lines = ["```mermaid", "flowchart LR"]
    for key, title in LAYERS:
        members = [n for n in nodes if layer(n) == key]
        if not members:
            continue
        lines.append(f'    subgraph {key}["{title}"]')
        lines += [
            f'        {n}["{n.removeprefix("src_") if key == "src" else n}"]' for n in members
        ]
        lines.append("    end")
    lines += [f"    {a} --> {b}" for a, b in pairs]
    lines.append("```")
    return HEADER + "\n".join(lines) + "\n"


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != content:
            print(f"{OUT.relative_to(ROOT)} is stale: run python scripts/build_lineage.py")
            return 1
        return 0
    OUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({content.count(' --> ')} edges)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
