"""Business metrics from the PUBLISHED warehouse, queried as the read-only reporting role -
exactly what a consumer (analyst, BI tool) can see. Writes docs/business_metrics.md and, with
--update-readme, the marked headline block of README.md. Every number is computed here.

Only metrics the dataset supports: orders, GMV, AOV, payments, delivery lead time and
lateness, cancellations, sellers, categories, reviews, repeat customers.

Usage: docker compose run --rm dev python scripts/business_report.py [--update-readme]
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from sqlalchemy import Connection, text

from olist_platform.config import Role
from olist_platform.database.engine import get_engine

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "business_metrics.md"
README_START, README_END = "<!-- BUSINESS:START -->", "<!-- BUSINESS:END -->"
MIN_SAMPLE = 500  # rankings only include groups with at least this many orders

# Same rule as the WARNING dbt test assert_monthly_order_volume_is_stable
EDGE_MONTHS_SQL = """
    WITH v AS (
        SELECT year_month, orders,
               avg(orders) OVER (ORDER BY month_start ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) AS t
        FROM marts.mart_sales)
    SELECT year_month FROM v WHERE t IS NOT NULL AND orders < 0.1 * t
"""


def brl(v: Any) -> str:
    return f"R$ {Decimal(v):,.2f}"


def pct(v: Any) -> str:
    return f"{Decimal(v) * 100:.1f}%"


def one(conn: Connection, sql: str, **p: Any) -> Any:
    return conn.execute(text(sql), p).one()


def rows(conn: Connection, sql: str, **p: Any) -> list[Any]:
    return conn.execute(text(sql), p).all()


def table(header: list[str], body: list[list[Any]]) -> list[str]:
    out = [
        "| " + " | ".join(header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in body]
    return out


def build(conn: Connection) -> tuple[str, str]:
    edge = {r[0] for r in rows(conn, EDGE_MONTHS_SQL)}
    h = one(
        conn,
        """
        SELECT count(*) AS orders,
               count(*) FILTER (WHERE is_delivered) AS delivered,
               count(*) FILTER (WHERE is_canceled) AS canceled,
               sum(order_value) FILTER (WHERE NOT is_canceled) AS gmv,
               sum(order_value) FILTER (WHERE NOT is_canceled AND item_count > 0)
                 / count(*) FILTER (WHERE NOT is_canceled AND item_count > 0) AS aov,
               sum(payment_value) AS payments,
               min(purchased_at)::date AS first_day, max(purchased_at)::date AS last_day
        FROM warehouse.fct_orders""",
    )
    d = one(
        conn,
        """
        SELECT avg(delivery_lead_days) AS avg_days,
               percentile_cont(0.5) WITHIN GROUP (ORDER BY delivery_lead_days) AS median_days,
               percentile_cont(0.9) WITHIN GROUP (ORDER BY delivery_lead_days) AS p90_days,
               avg(estimated_lead_days) AS promised_days,
               avg(is_late::int) AS late_rate
        FROM warehouse.fct_orders WHERE is_delivered""",
    )
    c = one(
        conn,
        """
        SELECT count(*) AS persons, avg(is_repeat_customer::int) AS repeat_rate
        FROM warehouse.dim_customer""",
    )
    r = one(
        conn,
        """
        SELECT avg(review_score) AS avg_score, count(*) AS reviews,
               avg(has_comment::int) AS comment_rate FROM warehouse.fct_reviews""",
    )
    late_vs_ontime = rows(
        conn,
        """
        SELECT CASE WHEN f.is_late THEN 'late' ELSE 'on time' END AS delivery,
               count(*) AS reviews, round(avg(r.review_score), 2) AS avg_score,
               avg((r.review_score <= 2)::int) AS low_score_share
        FROM warehouse.fct_reviews r JOIN warehouse.fct_orders f USING (order_id)
        WHERE f.is_delivered GROUP BY 1 ORDER BY 1""",
    )
    sellers = one(
        conn,
        """
        WITH s AS (SELECT revenue, ntile(10) OVER (ORDER BY revenue DESC) AS decile
                   FROM marts.mart_seller_performance)
        SELECT count(*) AS sellers,
               sum(revenue) FILTER (WHERE decile = 1) / sum(revenue) AS top_decile_share
        FROM s""",
    )

    lines = [
        "# Business metrics: Olist v2",
        "",
        f"Generated by `scripts/business_report.py` on {datetime.now(UTC):%Y-%m-%d} "
        f"(commit `{os.environ.get('REPORT_GIT_COMMIT', 'n/a')}`) from the **published** "
        "`marts`/`warehouse` schemas, queried as the read-only `olist_reporting` role. "
        "Do not edit by hand.",
        "",
        "**Reading guide.** Order data spans "
        f"{h.first_day} to {h.last_day}. Months flagged *edge* ({', '.join(sorted(edge))}) "
        "have under 10% of their trailing 3-month volume: they are incomplete periods at the "
        "edges of the extract (the WARNING rule `assert_monthly_order_volume_is_stable`), not "
        "business collapses, and must not be read as trends. GMV and AOV exclude canceled/"
        "unavailable orders; definitions are in [data_model.md](data_model.md).",
        "",
        "## Headline",
        "",
        *table(
            ["Metric", "Value"],
            [
                ["Orders", f"{h.orders:,}"],
                ["Delivered orders", f"{h.delivered:,} ({pct(Decimal(h.delivered) / h.orders)})"],
                [
                    "Canceled or unavailable",
                    f"{h.canceled:,} ({pct(Decimal(h.canceled) / h.orders)})",
                ],
                ["GMV (items + freight, non-canceled)", brl(h.gmv)],
                ["Average order value", brl(h.aov)],
                ["Payment volume (all payments)", brl(h.payments)],
                ["Customers (persons)", f"{c.persons:,}"],
                ["Repeat customers", pct(c.repeat_rate)],
                ["Sellers with sales", f"{sellers.sellers:,}"],
                ["Revenue share of the top 10% of sellers", pct(sellers.top_decile_share)],
                [
                    "Delivery lead time: mean / median / p90",
                    f"{d.avg_days:.1f} / {d.median_days:.1f} / {d.p90_days:.1f} days",
                ],
                ["Promised lead time (mean)", f"{d.promised_days:.1f} days"],
                ["Late deliveries", pct(d.late_rate)],
                ["Average review score", f"{r.avg_score:.2f} / 5 over {r.reviews:,} reviews"],
            ],
        ),
        "",
        "## Orders over time",
        "",
        *table(
            ["Month", "Orders", "Canceled", "Cancellation rate", "GMV", "AOV", "Note"],
            [
                [
                    m.year_month,
                    f"{m.orders:,}",
                    f"{m.canceled_orders:,}",
                    pct(m.cancellation_rate),
                    brl(m.gmv),
                    brl(m.avg_order_value) if m.avg_order_value else "-",
                    "edge" if m.year_month in edge else "",
                ]
                for m in rows(conn, "SELECT * FROM marts.mart_sales ORDER BY month_start")
            ],
        ),
        "",
        "## Payment volume by method",
        "",
        *table(
            ["Payment type", "Payments", "Volume", "Share of volume", "Avg instalments"],
            [
                [p.payment_type, f"{p.payments:,}", brl(p.volume), pct(p.share), f"{p.inst:.2f}"]
                for p in rows(
                    conn,
                    """
                SELECT payment_type, sum(payments) AS payments, sum(payment_volume) AS volume,
                       sum(payment_volume) / sum(sum(payment_volume)) OVER () AS share,
                       sum(avg_installments * payments) / sum(payments) AS inst
                FROM marts.mart_payment_methods GROUP BY 1 ORDER BY volume DESC""",
                )
            ],
        ),
        "",
        "## Delivery performance",
        "",
        "**Late deliveries are associated with lower review scores.** Reviews of delivered "
        "orders, by whether the order arrived after its promised date. This is a descriptive "
        "comparison, not a causal estimate: late and on-time orders can also differ in "
        "product, seller, region or season, and none of that is controlled for here.",
        "",
        *table(
            ["Delivery", "Reviews", "Avg score", "Share scoring 1-2"],
            [
                [x.delivery, f"{x.reviews:,}", x.avg_score, pct(x.low_score_share)]
                for x in late_vs_ontime
            ],
        ),
        "",
        f"Late-delivery rate by customer state (states with ≥ {MIN_SAMPLE:,} delivered "
        "orders), worst five and best five:",
        "",
    ]
    states = rows(
        conn,
        """
        SELECT customer_state, sum(delivered_orders) AS delivered,
               sum(late_orders)::numeric / sum(delivered_orders) AS late_rate,
               sum(avg_delivery_days * delivered_orders) / sum(delivered_orders) AS days
        FROM marts.mart_delivery_performance GROUP BY 1
        HAVING sum(delivered_orders) >= :n ORDER BY late_rate DESC""",
        n=MIN_SAMPLE,
    )
    lines += table(
        ["State", "Delivered", "Late rate", "Avg lead time (days)"],
        [
            [s.customer_state, f"{s.delivered:,}", pct(s.late_rate), f"{s.days:.1f}"]
            for s in [*states[:5], *states[-5:]]
        ],
    )
    lines += [
        "",
        "## Cancellation behaviour",
        "",
        *table(
            ["Primary payment type", "Orders", "Canceled", "Cancellation rate"],
            [
                [x.payment_type or "(no payment)", f"{x.orders:,}", f"{x.canceled:,}", pct(x.rate)]
                for x in rows(
                    conn,
                    """
                SELECT primary_payment_type AS payment_type, count(*) AS orders,
                       count(*) FILTER (WHERE is_canceled) AS canceled,
                       avg(is_canceled::int) AS rate
                FROM warehouse.fct_orders GROUP BY 1 ORDER BY orders DESC""",
                )
            ],
        ),
        "",
        "## Seller performance",
        "",
        "Top 10 sellers by revenue (ids truncated; sellers are anonymised in the source):",
        "",
        *table(
            [
                "Rank",
                "Seller (id prefix)",
                "State",
                "Orders",
                "Revenue",
                "Late rate",
                "Shipped after limit",
                "Avg review",
            ],
            [
                [
                    x.revenue_rank,
                    x.seller_id[:8],
                    x.seller_state,
                    f"{x.order_count:,}",
                    brl(x.revenue),
                    pct(x.late_rate or 0),
                    pct(x.shipped_after_limit_rate),
                    x.avg_review_score,
                ]
                for x in rows(
                    conn,
                    """
                SELECT * FROM marts.mart_seller_performance ORDER BY revenue_rank LIMIT 10""",
                )
            ],
        ),
        "",
        "## Product-category performance",
        "",
        "Top 10 categories by revenue:",
        "",
        *table(
            ["Category", "Orders", "Revenue", "Avg item price", "Avg review", "Late rate"],
            [
                [
                    x.category_name,
                    f"{x.orders:,}",
                    brl(x.revenue),
                    brl(x.avg_item_price),
                    x.avg_review_score,
                    pct(x.late_rate or 0),
                ]
                for x in rows(
                    conn,
                    """SELECT * FROM marts.mart_category_performance
                                   ORDER BY revenue DESC LIMIT 10""",
                )
            ],
        ),
        "",
        f"Lowest-rated categories (≥ {MIN_SAMPLE:,} orders):",
        "",
        *table(
            ["Category", "Orders", "Avg review", "Late rate"],
            [
                [x.category_name, f"{x.orders:,}", x.avg_review_score, pct(x.late_rate or 0)]
                for x in rows(
                    conn,
                    """SELECT * FROM marts.mart_category_performance
                                   WHERE orders >= :n ORDER BY avg_review_score LIMIT 5""",
                    n=MIN_SAMPLE,
                )
            ],
        ),
        "",
        "## Review score distribution",
        "",
        *table(
            ["Score", "Reviews", "Share", "With comment"],
            [
                [x.review_score, f"{x.reviews:,}", pct(x.share), pct(x.comment_share)]
                for x in rows(
                    conn,
                    """
                SELECT review_score, sum(reviews) AS reviews,
                       sum(reviews)::numeric / sum(sum(reviews)) OVER () AS share,
                       sum(reviews_with_comment)::numeric / sum(reviews) AS comment_share
                FROM marts.mart_review_distribution GROUP BY 1 ORDER BY 1""",
                )
            ],
        ),
        "",
    ]

    late, ontime = (next(x for x in late_vs_ontime if x.delivery == k) for k in ("late", "on time"))
    headline = "\n".join(
        [
            "Generated by `scripts/business_report.py` from the published marts (reporting role). "
            "Full report: [docs/business_metrics.md](docs/business_metrics.md).",
            "",
            *table(
                ["Business question", "Answer from the published marts"],
                [
                    [
                        "How much was sold?",
                        f"{h.orders:,} orders, GMV {brl(h.gmv)}, "
                        f"AOV {brl(h.aov)}, {h.first_day} to {h.last_day}",
                    ],
                    [
                        "How reliable is delivery?",
                        f"mean lead time {d.avg_days:.1f} days (median {d.median_days:.1f}) vs "
                        f"{d.promised_days:.1f} promised on average; "
                        f"{pct(d.late_rate)} of deliveries late",
                    ],
                    [
                        "Are late orders reviewed worse?",
                        f"late orders average {late.avg_score} stars vs "
                        f"{ontime.avg_score} on time; {pct(late.low_score_share)} of late "
                        f"orders score 1-2 vs {pct(ontime.low_score_share)}",
                    ],
                    [
                        "Do customers come back?",
                        f"{pct(c.repeat_rate)} of {c.persons:,} customers "
                        "placed more than one order",
                    ],
                    [
                        "How concentrated are sellers?",
                        f"the top 10% of {sellers.sellers:,} sellers "
                        f"earn {pct(sellers.top_decile_share)} of revenue",
                    ],
                    [
                        "Which periods are unreliable?",
                        f"{', '.join(sorted(edge))}: incomplete edge months, flagged automatically",
                    ],
                ],
            ),
        ]
    )
    return "\n".join(lines), headline


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update-readme", action="store_true")
    args = parser.parse_args()
    with get_engine(Role.REPORTING).connect() as conn:
        report, headline = build(conn)
    OUT.write_text(report, encoding="utf-8")
    if args.update_readme:
        readme_path = ROOT / "README.md"
        readme = readme_path.read_text(encoding="utf-8")
        start, end = readme.index(README_START), readme.index(README_END)
        readme = readme[: start + len(README_START)] + "\n" + headline + "\n" + readme[end:]
        readme_path.write_text(readme, encoding="utf-8")
    print(headline)
    return 0


if __name__ == "__main__":
    sys.exit(main())
