"""The README is part of the deliverable: its 20 sections must stay in the mandated order,
with no placeholders, and its measured blocks must be generated rather than typed."""

from __future__ import annotations

import re
from pathlib import Path

README = (Path(__file__).resolve().parents[2] / "README.md").read_text(encoding="utf-8")

REQUIRED = [
    "Business Question",
    "Business Problem",
    "Objective",
    "Measured Results",
    "Architecture Diagram",
    "Data Flow",
    "Dataset",
    "Data Model",
    "Data Quality Strategy",
    "Orchestration",
    "Observability",
    "Benchmark",
    "Engineering Decisions",
    "Trade-offs",
    "Failure Cases",
    "What Failed and What I Changed",
    "Known Limitations",
    "How to Run",
    "How to Test",
    "Final Answer to the Business Question",
]


def test_sections_are_all_present_in_the_mandated_order() -> None:
    sections = re.findall(r"^## (\d+)\. (.+)$", README, re.M)
    assert [title for _, title in sections] == REQUIRED
    assert [int(n) for n, _ in sections] == list(range(1, 21))


def test_no_placeholder_text_remains() -> None:
    for marker in ("*Pending", "Filled by `scripts/", "CHANGE_ME", "TODO"):
        assert marker not in README, marker


def test_measured_blocks_are_generated_by_scripts() -> None:
    for start, end, script in (
        ("<!-- BENCHMARK:START -->", "<!-- BENCHMARK:END -->", "scripts/benchmark.py"),
        ("<!-- BUSINESS:START -->", "<!-- BUSINESS:END -->", "scripts/business_report.py"),
    ):
        block = README.split(start)[1].split(end)[0]
        assert f"Generated by `{script}`" in block or f"Measured by `{script}`" in block
        assert "|" in block  # a filled table, not a placeholder
