"""The README is part of the deliverable: its sections must stay in the agreed order, with
no placeholders, its measured blocks must be generated rather than typed, and every relative
link must point to a file that exists."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
README = (ROOT / "README.md").read_text(encoding="utf-8")

REQUIRED = [
    "What problem does this solve?",
    "Architecture",
    "Engineering challenges",
    "Technology stack",
    "Data model",
    "Data quality",
    "Orchestration",
    "Observability",
    "Testing",
    "CI/CD",
    "Performance",
    "Business insight",
    "Quick start",
    "Repository structure",
    "Known limitations",
    "Future improvements",
]


def test_sections_are_all_present_in_the_mandated_order() -> None:
    sections = re.findall(r"^## (\d+)\. (.+)$", README, re.M)
    assert [title for _, title in sections] == REQUIRED
    assert [int(n) for n, _ in sections] == list(range(1, len(REQUIRED) + 1))


def test_no_placeholder_text_remains() -> None:
    for marker in ("*Pending", "Filled by `scripts/", "CHANGE_ME", "TODO"):
        assert marker not in README, marker


def test_measured_blocks_are_generated_by_scripts() -> None:
    for start, end, script in (
        ("<!-- BENCHMARK:START -->", "<!-- BENCHMARK:END -->", "scripts/benchmark.py"),
        ("<!-- BUSINESS:START -->", "<!-- BUSINESS:END -->", "scripts/business_report.py"),
    ):
        block = README.split(start)[1].split(end)[0]
        assert f"Generated by `{script}`" in block or f"Measured by `{script}`" in block
        assert "|" in block  # a filled table, not a placeholder


def test_relative_links_resolve() -> None:
    targets = re.findall(r"\]\(((?!https?://|#)[^)#]+)", README)
    assert targets
    missing = [t for t in targets if not (ROOT / t).exists()]
    assert missing == []


def test_ci_badge_points_to_the_real_workflow() -> None:
    # The badge reflects the live GitHub Actions status of the workflow committed here
    badges = re.findall(r"actions/workflows/([\w.-]+)/badge\.svg", README)
    assert badges == ["ci.yml"]
    assert (ROOT / ".github" / "workflows" / "ci.yml").exists()
